"""Permission revisions catalog and environment drafts

Revision ID: 0002_catalog
Revises: 0001_identity_groups
"""

import sqlalchemy as sa
from alembic import op

revision = "0002_catalog"
down_revision = "0001_identity_groups"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission_policy_revisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_permission_policy_revisions_created_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission_policy_revisions")),
    )
    op.create_table(
        "template_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("runtime_kind", sa.String(length=8), nullable=False),
        sa.Column("guest_family", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "guest_family IN ('LINUX','WINDOWS')", name=op.f("ck_template_versions_family")
        ),
        sa.CheckConstraint(
            "runtime_kind != 'LXC' OR guest_family = 'LINUX'",
            name=op.f("ck_template_versions_lxc_linux"),
        ),
        sa.CheckConstraint(
            "runtime_kind IN ('LXC','QEMU')", name=op.f("ck_template_versions_kind")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_template_versions_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_versions")),
    )
    op.create_table(
        "policy_limits",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("value >= 0", name=op.f("ck_policy_limits_nonnegative")),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["permission_policy_revisions.id"],
            name=op.f("fk_policy_limits_revision_id_permission_policy_revisions"),
        ),
        sa.PrimaryKeyConstraint("revision_id", "key", name=op.f("pk_policy_limits")),
    )
    op.create_table(
        "policy_permissions",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["permission_policy_revisions.id"],
            name=op.f("fk_policy_permissions_revision_id_permission_policy_revisions"),
        ),
        sa.PrimaryKeyConstraint("revision_id", "key", name=op.f("pk_policy_permissions")),
    )
    op.create_table(
        "profile_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("template_version_id", sa.Uuid(), nullable=False),
        sa.Column("memory_mib", sa.Integer(), nullable=False),
        sa.Column("vcpu", sa.Integer(), nullable=False),
        sa.Column("cpu_millicredits", sa.Integer(), nullable=False),
        sa.Column("disk_gib", sa.Integer(), nullable=False),
        sa.Column("network_mode", sa.String(length=16), nullable=False),
        sa.Column("internet_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "network_mode IN ('ISOLATED','GROUP_LAN')", name=op.f("ck_profile_versions_network")
        ),
        sa.CheckConstraint(
            "memory_mib > 0 AND vcpu > 0 AND cpu_millicredits > 0 AND disk_gib > 0",
            name=op.f("ck_profile_versions_resources"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_profile_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["template_version_id"],
            ["template_versions.id"],
            name=op.f("fk_profile_versions_template_version_id_template_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_versions")),
    )
    op.create_table(
        "teacher_policy_assignments",
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["permission_policy_revisions.id"],
            name=op.f("fk_teacher_policy_assignments_revision_id_permission_policy_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["users.id"],
            name=op.f("fk_teacher_policy_assignments_teacher_id_users"),
        ),
        sa.PrimaryKeyConstraint("teacher_id", name=op.f("pk_teacher_policy_assignments")),
    )
    op.create_table(
        "demo_profile_grants",
        sa.Column("revision_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_version_id"],
            ["profile_versions.id"],
            name=op.f("fk_demo_profile_grants_profile_version_id_profile_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["permission_policy_revisions.id"],
            name=op.f("fk_demo_profile_grants_revision_id_permission_policy_revisions"),
        ),
        sa.PrimaryKeyConstraint(
            "revision_id", "profile_version_id", name=op.f("pk_demo_profile_grants")
        ),
    )
    op.create_table(
        "environments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("owner_teacher_id", sa.Uuid(), nullable=False),
        sa.Column("profile_version_id", sa.Uuid(), nullable=False),
        sa.Column("demo_profile_version_id", sa.Uuid(), nullable=False),
        sa.Column("permission_revision_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["demo_profile_version_id"],
            ["profile_versions.id"],
            name=op.f("fk_environments_demo_profile_version_id_profile_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_environments_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["owner_teacher_id"], ["users.id"], name=op.f("fk_environments_owner_teacher_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["permission_revision_id"],
            ["permission_policy_revisions.id"],
            name=op.f("fk_environments_permission_revision_id_permission_policy_revisions"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_version_id"],
            ["profile_versions.id"],
            name=op.f("fk_environments_profile_version_id_profile_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_environments")),
        sa.UniqueConstraint(
            "owner_teacher_id", "request_id", name=op.f("uq_environments_owner_teacher_id")
        ),
    )
    op.create_index(op.f("ix_environments_group_id"), "environments", ["group_id"], unique=False)
    op.create_index(
        op.f("ix_environments_owner_teacher_id"), "environments", ["owner_teacher_id"], unique=False
    )
    op.execute("""
        CREATE FUNCTION lab_catalog_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN
          RAISE EXCEPTION 'Catalog revisions are immutable; create a new revision';
        END $$
    """)
    for table in (
        "template_versions",
        "profile_versions",
        "permission_policy_revisions",
        "policy_permissions",
        "policy_limits",
        "demo_profile_grants",
    ):
        op.execute(
            f"CREATE TRIGGER immutable_revision BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION lab_catalog_immutable()"
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_environments_owner_teacher_id"), table_name="environments")
    op.drop_index(op.f("ix_environments_group_id"), table_name="environments")
    op.drop_table("environments")
    op.drop_table("demo_profile_grants")
    op.drop_table("teacher_policy_assignments")
    op.drop_table("profile_versions")
    op.drop_table("policy_permissions")
    op.drop_table("policy_limits")
    op.drop_table("template_versions")
    op.drop_table("permission_policy_revisions")
    op.execute("DROP FUNCTION lab_catalog_immutable()")
    # ### end Alembic commands ###
