"""Durable operations and worker heartbeats

Revision ID: 0003_operations
Revises: 0002_catalog
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003_operations"
down_revision = "0002_catalog"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_heartbeats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_heartbeats")),
    )
    op.create_table(
        "operations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("actor_id", sa.Uuid(), nullable=False),
        sa.Column("owner_teacher_id", sa.Uuid(), nullable=False),
        sa.Column("environment_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("request_digest", sa.String(length=64), nullable=False),
        sa.Column("expected_version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("fence", sa.BigInteger(), nullable=False),
        sa.Column("lease_owner", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "(state = 'RUNNING') = (lease_until IS NOT NULL AND lease_owner IS NOT NULL)",
            name=op.f("ck_operations_running_lease"),
        ),
        sa.CheckConstraint(
            "(state IN ('SUCCEEDED','FAILED','CANCELLED')) = (finished_at IS NOT NULL)",
            name=op.f("ck_operations_terminal_time"),
        ),
        sa.CheckConstraint(
            "state IN ('QUEUED','RUNNING','WAITING_NODE','WAITING_RECONCILIATION',"
            "'SUCCEEDED','FAILED','CANCEL_REQUESTED','CANCELLED')",
            name=op.f("ck_operations_state"),
        ),
        sa.CheckConstraint(
            "attempt >= 0 AND fence >= 0 AND version > 0", name=op.f("ck_operations_counters")
        ),
        sa.CheckConstraint("expected_version > 0", name=op.f("ck_operations_expected_version")),
        sa.ForeignKeyConstraint(
            ["actor_id"], ["users.id"], name=op.f("fk_operations_actor_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environments.id"],
            name=op.f("fk_operations_environment_id_environments"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_teacher_id"], ["users.id"], name=op.f("fk_operations_owner_teacher_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("actor_id", "request_id", name=op.f("uq_operations_actor_id")),
    )
    op.create_index(
        "ix_operation_dispatch", "operations", ["kind", "state", "available_at"], unique=False
    )
    op.create_index(
        op.f("ix_operations_owner_teacher_id"), "operations", ["owner_teacher_id"], unique=False
    )
    op.create_index(
        "uq_operation_active_environment",
        "operations",
        ["environment_id"],
        unique=True,
        postgresql_where=sa.text("state NOT IN ('SUCCEEDED','FAILED','CANCELLED')"),
    )
    op.create_table(
        "operation_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_operation_events_operation_id_operations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_events")),
        sa.UniqueConstraint(
            "operation_id", "version", name=op.f("uq_operation_events_operation_id")
        ),
    )
    op.create_index(
        op.f("ix_operation_events_operation_id"), "operation_events", ["operation_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_events_operation_id"), table_name="operation_events")
    op.drop_table("operation_events")
    op.drop_index(
        "uq_operation_active_environment",
        table_name="operations",
        postgresql_where=sa.text("state NOT IN ('SUCCEEDED','FAILED','CANCELLED')"),
    )
    op.drop_index(op.f("ix_operations_owner_teacher_id"), table_name="operations")
    op.drop_index("ix_operation_dispatch", table_name="operations")
    op.drop_table("operations")
    op.drop_table("worker_heartbeats")
    # ### end Alembic commands ###
